version: '2.4'
services:
  playgames-backend:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIN_USER=${MAIN_USER}
      - MAIL_PASS=${MAIL_PASS}
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
